### ISSUE TITLE
Works at the test page but not at xbox.com

### ISSUE THREAD

**Issue by benoe77** [idolize/xcloud-keyboard-mouse#1]
When I want to start a game on xbox.com, the launcher notifies me that there is no controller connected. And it isn't working at any game I tried.
Controls are working at https://gamepad-tester.com/

**Comment by benoe77** [comment]
Yes, as hinted in another issue, it works on https://www.xbox.com/en-US/play/ but not at my local site at https://www.xbox.com/hu-HU/play

**Comment by idolize** [comment]
Hey @benoe77 thanks for filing the issue. I've submitted a new version (v1.1) to the Chrome Web Store which should enable the extension on all locale pages of xcloud now (not just en-us).

Let me know if it works for you!

**Comment by benoe77** [comment]
It works, thanks!
