### ISSUE TITLE
reembolso ou a resolução do problema 

### ISSUE THREAD

**Issue by neto68** [idolize/xcloud-keyboard-mouse#100]
### Bug description

antes da compra o produto apresentava ótima performance, mas agora esta travando constantemente a sensibilidade de qualquer jogo 

### Extension Version

3.2

### What browser(s) are you seeing the problem on?

Other (Please specify)

### Other browser

xcloud (xbox)

### Browser version number

Versão 108.0.5359.125 (Versão oficial) 64 bits

**Comment by idolize** [comment]
Estou esperando a versão 3.3 entrar no ar, mas essa versão deve restaurar a sensibilidade do mouse exatamente como era antes. Obrigada! Desculpe por qualquer problema.
