### ISSUE TITLE
mouse stopping and returning

### ISSUE THREAD

**Issue by TIOZINdaMAGIA** [idolize/xcloud-keyboard-mouse#101]
### Bug description

mouse parando e voltando.
ou ele puxa para o lado comtrario da açao

### Extension Version

3.2

### What browser(s) are you seeing the problem on?

Chrome

### Other browser

chrome

**Comment by idolize** [comment]
Thanks for letting me know. I've reverted the changes to the movement from 3.2 in a new hotfix release 3.3 which is currently in review and should be live on the Chrome store in about a day.
