### ISSUE TITLE
Pay to use

### ISSUE THREAD

**Issue by therealtutugoy** [idolize/xcloud-keyboard-mouse#103]
This is extension was better without paying money fix this. Nobody will get this extension if you ask them for money just for a extension. I know this is only 4 dollars but at least make it so that it is premium and make a free version!!!

**Comment by idolize** [comment]
Hi thanks for the feedback. I felt that my time and effort is worth a few dollars, especially that with this extension you get permanent mouse and keyboard support for xCloud, plus all the other UI for customization and options for editing your controls.

There’s still a free trial, but I hope you’ll all see the value in the extension and will want to support it to keep it going. But I understand if not.
