### ISSUE TITLE
It's time to say goodbye

### ISSUE THREAD

**Issue by cutocu** [idolize/xcloud-keyboard-mouse#104]
it was good to play while it lasted, it's a pity that the extension was paid and I won't be able to pay. I understand the reasons for the extension being paid, but now, I will no longer be able to play even though I have a controller, my computer is a chromebook and I signed the gamepass on xcloud because there was no way to buy a computer really made for games, I got one 3 months code for the gamepass, but now I can't anymore. You are not wrong for putting the paid extension, you must be short of money or something, but it was worth it, I had fun for a while, thanks

**Comment by idolize** [comment]
@cutocu Thank you for being respectful, and I understand.

For what it's worth - my goal isn't to gouge people who really cannot afford the $4. I will look into localized pricing or possibly a free ad-supported version of some sort, but it will probably take time to figure out.
