### ISSUE TITLE
No option for change view button

### ISSUE THREAD

**Issue by julerobb1** [idolize/xcloud-keyboard-mouse#11]
I have noted there is no option for mapping control to the following button listed as change view (link is an image from bing) : https://dlassets-ssl.xboxlive.com/public/content/1bb39ca3-2391-44a2-9873-d5a2097b632b/GameManual/f1ad788e-3a83-40f1-b7d4-6a8cd0d00bd3/en-US/ButtonMap_Video_v8.jpg

and I was wondering why this is and if there is a mapping for it, how to map one. It is needed for forza horizon  4 and 5.

**Comment by idolize** [comment]
Hi! I think this button is referred to as "Select" in the UI - apologies if the naming is confusing. I may consider renaming these mappings or including little button images next to the names.

<img width="504" alt="Screen Shot 2021-12-09 at 12 59 57 PM" src="https://user-images.githubusercontent.com/635005/145450641-c1b49f20-5d70-481a-9135-9b2c11a3c995.png">

But let me know if this doesn't work for you!
