### ISSUE TITLE
For some reason it's unusable all of a sudden.

### ISSUE THREAD

**Issue by scottwills1998** [idolize/xcloud-keyboard-mouse#113]
### Bug description

Literally I fell asleep last night and it was working but today it's not working. I've tried different presets, but it's not connecting to the xcloud at all anymore. Can't input the buttons needed to get though the start up screen. I wouldn't have had a problem with it if it was still free, but the fact that I paid for it and now the quality has gone down is seriously frustrating.

### Extension Version

3.3

### What browser(s) are you seeing the problem on?

Chrome

**Comment by scottwills1998** [comment]
Literally almost as is by magic I left this page went back and the presets were working again. My bad!

**Comment by idolize** [comment]
No worries. I think there are a few weird cases where it 'disconnects' from the page (probably having to do with the new Manifest v3 service worker approach chrome is moving everyone to for extensions), but typically just refreshing xcloud should fix it.

**Comment by scottwills1998** [comment]
Yep I think you're right, just had never happened before. It's a great app thank you for your response!
________________________________
