### ISSUE TITLE
"This email has been used too many times"

### ISSUE THREAD

**Issue by Lirsin** [idolize/xcloud-keyboard-mouse#118]
This issue shows up after continuous use of the extension and doesn't show any way of fixing the problem. This makes it so you can't even use something you've payed for anymore. it's not like I abused the login system or anything. Pretty annoying...

**Comment by idolize** [comment]
@Lirsin are you still seeing this? When are you getting this message? If it's during login, this should only happen if you activated on more than 10 devices
