### ISSUE TITLE
MAIL NEVER ARRIVES

### ISSUE THREAD

**Issue by alexsmtz** [idolize/xcloud-keyboard-mouse#120]
when it asks me to put my email in order to log in it says a mail will arrive with log in link.
i even paid for it and it doesnt work... 
i got the receipt mail but never the log in email.

**Comment by idolize** [comment]
Hi can you post the email you used or message me directly with it? I can look into it for you - sorry for the trouble.

**Comment by alexsmtz** [comment]
The email i used is
***@***.***
I actually emailed you from there yesterday.
Thanks.

**Comment by idolize** [comment]
I think because you replied to this via email GitHub redacted the address (it just shows up as `***@***.***`). Can you send me another email and mention this thread or your github name "alexsmtz"? Thanks!
