### ISSUE TITLE
refund please

### ISSUE THREAD

**Issue by Joshthegamer28** [idolize/xcloud-keyboard-mouse#122]
### Bug description

I try to buy it at first it wasn't working, so I gave up but it charged me and when I went to go put in my email it said I wasn't in the system so can have a refund.

### Extension Version

the latest version as of 3/1/2023

### What browser(s) are you seeing the problem on?

Chrome

### Browser version number

the latest version of Chrome as of 3/1/23

**Comment by idolize** [comment]
Hi what email did you use? I can fix it for you.

**Comment by idolize** [comment]
@Joshthegamer28 I can update the payment record email if you let me know

**Comment by Joshthegamer28** [comment]
This one
