### ISSUE TITLE
ERROR DE KEYBOARD AND MOUSE LA EXTENSION QUIERO PRONTAS SOLUCIONES

### ISSUE THREAD

**Issue by dariolatorreb26** [idolize/xcloud-keyboard-mouse#130]
### Bug description

I would like you to solve these extension problems that are occurring up to now and have not been solved so far, these problems have been occurring for a long time, dear friend, so please put a lot of batteries into it.
The problems are that when moving the camera in shotter or racing games it doesn't run smoothly as it should normally be in any game when it is installed on the computer, for example the camera runs very smoothly without any problem of lag or tear or motion blur. So please try to do as much as possible to remove those big errors that always appear in this keyboard and mouse extension for xcloud gaming. Thank you very much for solving the error. Thank you very much and regards.

### Extension Version

3.5

### What browser(s) are you seeing the problem on?

Chrome

### Other browser

edge 

### Browser version number

 111.0.5563.65 (Build oficial) (64 bits)

**Comment by idolize** [comment]
I think your request is smoother movement of the control stick via the mouse? I can look into this some in the future - thanks for the feedback

**Comment by dariolatorreb26** [comment]
please I want a prompt solution of this extension as it has bugs and does not go very well when running any game in motion camera goes super slow
________________________________
De: David Idol ***@***.***>
Enviado: viernes, 24 de marzo de 2023 5:07 p. m.
Para: idolize/xcloud-keyboard-mouse ***@***.***>
Cc: dariolatorreb26 ***@***.***>; Author ***@***.***>
Asunto: Re: [idolize/xcloud-keyboard-mouse] ERROR DE KEYBOARD AND MOUSE LA EXTENSION QUIERO PRONTAS SOLUCIONES (Issue #130)


Closed #130<https://github.com/idolize/xcloud-keyboard-mouse/issues/130> as completed.
