### ISSUE TITLE
safari build successful, but can't activate plugin on Mac

### ISSUE THREAD

**Issue by DaveFlashNL** [idolize/xcloud-keyboard-mouse#14]
![Schermafbeelding 2021-12-11 om 15 35 02](https://user-images.githubusercontent.com/72280178/145680385-68ecefe1-7420-43f8-8217-37f79228e6ca.png)

 translation it says something about an unsupported manifest version, how to fix? #13 # #

**Comment by idolize** [comment]
Hi I see you are trying to build and run for Safari - make sure you do `npm install` and then `npm run build:safari` (NOT `npm run build` - that will only work on Chrome) first, then open the Xcode project and run from there (you will also need Safari developer mode enabled)

**Comment by DaveFlashNL** [comment]
> Hi I see you are trying to build and run for Safari - make sure you do `npm install` and then `npm run build:safari` (NOT `npm run build` - that will only work on Chrome) first, then open the **Xcode project** and run from there (you will also need Safari developer mode enabled)
> 
> https://github.com/idolize/xcloud-keyboard-mouse/blob/master/CONTRIBUTING.md#build

I'm a bit of a novice at this, still learning, but to which directory must I do npm install / nom build/run?

**Comment by DaveFlashNL** [comment]
yes, worked a charm, new build let it self be activated immediately in safari!

**Comment by idolize** [comment]
Awesome! Glad you got it working. I'm still in panning on setting up  a more official Safari release, but it may take more time due to #13
