### ISSUE TITLE
Export/Import Present as an option

### ISSUE THREAD

**Issue by dbz2k** [idolize/xcloud-keyboard-mouse#15]
It would be nice to be able to export presents, and easily share and import them.

**Comment by idolize** [comment]
Hey @dbz2k thanks for the feature request. I'm curious- what is your use case for this? Is it to share presets with other people online or friends?

I've also toyed with the idea of automatically-activating or triggering certain presets based on what game you start playing. Is this something you think would be useful?

**Comment by dbz2k** [comment]
My main use case was being able to import the presets to my other computers. It would be nice having having automatically-activating presents.

**Comment by idolize** [comment]
Thanks. FYI your presets should sync across computers if you are signed into the same Chrome account (and have Chrome sync enabled, which it is by default). I believe Edge + MS account works the same way.

**Comment by idolize** [comment]
@dbz2k I just launched an export/import feature in version 2.5 (live now on Chrome Web Store)
