### ISSUE TITLE
Middle / Aux Mousedown events aren't supported

### ISSUE THREAD

**Issue by bo-carey** [idolize/xcloud-keyboard-mouse#16]
## Problem
I love this project! It would be great to see middle mouse click supported and even side buttons! I have included where the change would need to be made and what would need to be added to support it.

## Proposed Solution
this change could go in src/browser/browserEventProcessor.ts under mouse options (line 135ish):
```js
listeners.auxclick = function auxclick(e) {
  const { button } = e as MouseEvent;
  const buttonName = `Aux${button}`; // will be named something like "Aux3"
  handleKeyEvent(buttonName, simulateBtnUnpress, simulateAxeDirUnpress);
};
```

I know you would then have to add some things to your mappings file and change the way you check that they are using mouse events, but I am willing to contribute if it is too much!

**Comment by Jafetter** [comment]
Friend, would add a way to work the mouse correctly in the kiwi browser on android.

**Comment by idolize** [comment]
@bo-carey Thanks for the suggestion! I'd be happy to add support for more mouse buttons.

I was not aware of the [`auxclick` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event). It looks like [`mousedown` also supports multiple buttons/middle click types with `event.button`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button), but I'll have to give it a try with a mouse on my end!

**Comment by bo-carey** [comment]
Awesome! Please let me know if you ever open the repo up for contributions! 👍

**Comment by bo-carey** [comment]
@idolize I would like to take a crack at this if you would have me on as a contributor! I can submit a PR for your review if you are able to!

**Comment by idolize** [comment]
Thanks for the PR! I've merged the changes, and will work on pushing this change to the Chrome store as a part of the upcoming 3.0 release.
