### ISSUE TITLE
Kiwi browser support

### ISSUE THREAD

**Issue by mariustmasi2020** [idolize/xcloud-keyboard-mouse#20]
Hi there,u tryed on Kiwy browser Android where I can add-ons google ,keyboard works perfect but mouse keep tell me to click anywhere to a able .can you please help us..m and k works well on GeForce now android so I can use both for sure

**Comment by idolize** [comment]
Hi have you looked at https://github.com/idolize/xcloud-keyboard-mouse/issues/8? It seems the user in that post was maybe able to get it working?
I don't have an Android device with Kiwi browser to look into - but the extension uses the pointer lock API.

**Comment by idolize** [comment]
Duplicate of #8
