### ISSUE TITLE
Extension messed up my gamepad mapping on chrome

### ISSUE THREAD

**Issue by Schwingi** [idolize/xcloud-keyboard-mouse#21]
First thanks a lot for this extension, worked well on my setup. BUT when I wanted to get back to my controller, the button mapping was all messed up. Even on gamepad-tester the mapping is busted. I tried to remove the extension but the problem persist. Where can I "revert" the changes the extension made?

Thanks in advance, cheers

**Comment by idolize** [comment]
Hi! This extension does not (and can not) make any changes to your real controller or it's button mapping. All it does is pretend to be a different controller to your browser when the extension is enabled.

It must have been something else to do what you are describing, sorry.
