### ISSUE TITLE
Mouse sensitivity

### ISSUE THREAD

**Issue by jeremy10tie** [idolize/xcloud-keyboard-mouse#23]
hello ,the mouse needs improvement because it is not smooth when I move the mouse, you have to move the mouse several times to get the camera to rotate (not smooth, responsive,
feeling of slowness, delays), sometimes there is a feeling of slowness of 2/3 seconds to turn the camera completely even with a sensitivity of 99, I play on infinite halo and I also have this problem on back 4 blood

**Comment by idolize** [comment]
Hi @jeremy10tie you will very likely also need to increase the gamepad sensitivity in the game you are playing.

Unfortunately, the extension can only tell the game you have the "stick" tilted to its maximum, but in most games on controller that alone (on default in-game settings) doesn't necessarily mean very much movement of the camera. When you set the sensitivity to 99 in the extension it just means you max out the "stick" tilt with very little mouse movement - you still need to tell the game to handle stick movements more sensitively.

My advice is to turn down the sensitivity in the extension settings some and increase the gamepad sensitivity in the **in-game options** as much as possible.

**Comment by jeremy10tie** [comment]
I tried to modify the parameters and it does not change anything, it is not fluid it is slow and at times I have to move the mouse 4/5 times on the left instead of 1 movement of the mouse. Without xcloud I have already tested with a friend on the steam version with the same mouse and it's ultra fluid, it responds instantly and no slowness and no need to move the mouse many times for the camera

**Comment by idolize** [comment]
> Without xcloud I have already tested with a friend on the steam version with the same mouse and it's ultra fluid

Yeah unfortunately the PC versions are able to enable "mouse control mode" which the xcloud versions are not - thus this extension has to simulate controller stick movements by detecting mouse movements and the experience won't be 100% the same.

If you have more specific feedback or suggestions on how to improve please feel free to comment.
