### ISSUE TITLE
How do i start the extension??

### ISSUE THREAD

**Issue by erman44** [idolize/xcloud-keyboard-mouse#25]

**Comment by idolize** [comment]
Hi @erman44 - just install the extension and go to https://www.xbox.com/play/ - it should start working as soon as you launch a game. (Note the extension only works in browser, such as Chrome and Edge)

If you have any issues with it activating, try reinstalling the extension and reloading the page.

If you want to customize your bindings, open the extension by [pinning the icon to your toolbar](https://www.maketecheasier.com/pin-extensions-to-chrome-toolbar/) and clicking the icon to open the popup.

You can also test the extension is working at https://gamepad-tester.com/ (you should be able to control the "gamepad" via your mouse and keyboard)
