### ISSUE TITLE
Setting with Mouse G502 on R6 Extinction Xcloud

### ISSUE THREAD

**Issue by Djtenia22** [idolize/xcloud-keyboard-mouse#29]
I don't find a good setting for the AIM.
- i put 100 for sensitivity
- 5 for deadzone
and after between GHUB on logitech and the extension i can't find the good setting to be smooth.
there is a king of accélération on the movement with the mouse. # #

**Comment by idolize** [comment]
@Djtenia22 try lowering sensitivity in the extension settings and increasing it to max in the **in-game settings for your game**
