### ISSUE TITLE
where is the LS buttom

### ISSUE THREAD

**Issue by VjavierM** [idolize/xcloud-keyboard-mouse#3]
## Problem

no hay boton de LS

## Suggested solution

DEBERIAN AGREGAR UN BOTON

**Comment by idolize** [comment]
<img width="340" alt="Screenshot 2023-04-13 at 12 42 26 PM" src="https://user-images.githubusercontent.com/635005/231866258-ff5b3fe3-57e5-4fd5-ae61-139091938cfe.png">

You mean "left stick pressed"?
