### ISSUE TITLE
Option to disable "click anywhere to resume"

### ISSUE THREAD

**Issue by AndnixSH** [idolize/xcloud-keyboard-mouse#31]
This will be off-topic but can we have an extra option to disable "click anywhere to resume" when the tab or browser is out of focus?
I want the game to be running in background so I can at least hear something in background while waiting for lobby or something.

**Comment by idolize** [comment]
Oh yeah I actually had this at one point (essentially remove the default blur/focus listeners) but removed it as it was out of scope. I can definitely consider adding it back!

**Comment by AndnixSH** [comment]
A tampermonkey script would be ok if not in scope

**Comment by idolize** [comment]
FYI @AndnixSH I've added this in the latest v3 release of the extension, which is currently in review and should go live soon!
