### ISSUE TITLE
Profile switching using hotkeys

### ISSUE THREAD

**Issue by t0msk** [idolize/xcloud-keyboard-mouse#40]
Hello,

I use Microsoft Edge for playing in XCloud and I use it in kiosk mode so I don't have access to UI elements of browser, so I think it should be great to have access to switch between profiles with hotkeys, without clicking on extension :) For example one hotkey to load profile to left and another hotkey to load profile to right :)

**Comment by idolize** [comment]
I believe this should be [fairly straightforward to implement using `commands`](https://developer.chrome.com/docs/extensions/reference/commands/#handling-command-events).

I'm curious though - how are you able to set up and configure multiple profiles in the first place if you are in kiosk mode and cannot access the extension's icon and UI?

**Comment by t0msk** [comment]
I leave kiosk mode and set up everything what I need and then I have shortcut on desktop which will run Edge in kiosk mode right into XCloud, so it looks like "actual app".

**Comment by idolize** [comment]
Ah pretty cool! Yeah, I can look into adding this in the future. Pretty busy at the moment so no ETA (unless you want to submit a PR)

**Comment by t0msk** [comment]
Okay :) if you are interested I use these arguments:

`--window-size=1024,640 --force-device-scale-factor=1.2 --device-scale-factor=1.2  --kiosk "https://www.xbox.com/play"`

**Comment by Haisom** [comment]
great for games that uses different mapping like Watch Dogs aka walking controllers and vehicle controllers are totally different

**Comment by idolize** [comment]
FYI @t0msk I've added keyboard shortcuts for next/previous profile as well as hide/show cheatsheet in the latest v3 release of the extension, which is currently in review and should go live soon!
