### ISSUE TITLE
Floating area with buttons layout

### ISSUE THREAD

**Issue by pryan1check** [idolize/xcloud-keyboard-mouse#44]
## Problem

It is difficult to quickly remember the layout of the buttons, so you often have to open the extension. It is very uncomfortable

## Suggested solution
I propose to make a translucent area in which the layout of the buttons will be displayed.
[example](https://i.ibb.co/2syYxt9/2022-04-25-14-33-29.png)

**Comment by Kaedh** [comment]
I don't know if the owner is active, but I think is an interesting idea
I can implement.

**Comment by Kaedh** [comment]
I'll take a look and try to implement a prototype, later we see how it stays.

**Comment by Haisom** [comment]
and also add a hotkey to enable the foating mapping cheat, it's really hard to remember the way you mapped sometimes because almost every game require specific mapping for better suit km&m gameplay! thank you!!! <3

**Comment by idolize** [comment]
FYI @pryan1check I've added this in the latest v3 release of the extension, which is currently in review and should go live soon!
