### ISSUE TITLE
Using mouse lags the game

### ISSUE THREAD

**Issue by DarkSaber55** [idolize/xcloud-keyboard-mouse#46]
### Bug description

When I'm using a usb mouse, the game lags like hell. Not lagging that much when I'm using the trackpad though.

### Extension Version

Version 2.6

### What browser(s) are you seeing the problem on?

Chrome

### Browser version number

Version 101.0.4951.54

**Comment by Edu12579** [comment]
No extensor do celular o mouse não pega oque eu faço ??..
