### ISSUE TITLE
doesn't work for non US user's atleast for me

### ISSUE THREAD

**Issue by AlcatrazCrysis2** [idolize/xcloud-keyboard-mouse#5]
https://www.xbox.com/pl-PL/play?xr=shellnav 
this is the site where it doesn't work I tried literally everything and still nothing

**Comment by idolize** [comment]
Heads up I submitted a version 1.2 for review on the Chrome store which should address this. Once it goes live it should work as expected!

For now, try going to the game page and refreshing the page after you get to the game and see if that works.

**Comment by idolize** [comment]
Closing because the main issue (URL matching only working for `/en-US/`) has been fixed!
