### ISSUE TITLE
Scroll on 2 keybinds

### ISSUE THREAD

**Issue by MFR1337** [idolize/xcloud-keyboard-mouse#52]
## Problem

i wantet to add scroll to right and left shoulder button 

## Suggested solution

Maby add scroll up or scroll down to the sttings so id dosent doubble up

## Additional context

sorry for the bad english 
pls put this feature in i nned it for fortnite

**Comment by Haisom** [comment]
I really like that suggestion, but maybe beginning with middle mouse button detection is already a start. Mine does not work and it's a must for Watch Dogs 2

**Comment by anant-k-singh** [comment]
While assigning scroll to controls, it does not differentiate between mouse scroll up and down

**Comment by idolize** [comment]
Thanks - yes this is something I intend to add shortly.

**Comment by idolize** [comment]
FYI @MFR1337 I've added this in the latest v3 release of the extension, which is currently in review and should go live soon!
