### ISSUE TITLE
game is not detecting

### ISSUE THREAD

**Issue by wigorsnet** [idolize/xcloud-keyboard-mouse#6]
Can someone help me?

it working but doesn't working any game.

Chrome, edge and PT/ENG languages tested.
[
![ss](https://user-images.githubusercontent.com/78506359/143937376-225c4493-dcd6-4cbf-bea7-0c4a4658b54a.png)
](url)

**Comment by ricardo404** [comment]
Same thing around here. It doesn't detect the game but if you put the Preset to test the Gamepad test works correctly.
![image](https://user-images.githubusercontent.com/35298519/143953359-9022f558-da4c-48b4-ba3e-a04e074b85bd.png)

**Comment by ricardo404** [comment]
From what I saw, the friend above also uses Xcloud on PT-BR......

**Comment by idolize** [comment]
Heads up I submitted a version `1.2` for review on the Chrome store which should address this. Once it goes live it should work as expected!

For now, try going to the game page and refreshing the page after you get to the game and see if that works.

**Comment by ricardo404** [comment]
![image](https://user-images.githubusercontent.com/35298519/143973819-197857c5-4727-462b-9759-0588efa581f4.png)
Check. After I refreshed the page it normally enabled the function. I'm still wondering why I didn't do it. But it's alright.

**Comment by ricardo404** [comment]
Waiting for 1.2 to resolve definitively. Thank you @idolize .
