### ISSUE TITLE
I'm having mouse problems in Kiwi Browser 

### ISSUE THREAD

**Issue by Oxdf22** [idolize/xcloud-keyboard-mouse#74]
### Bug description

I tried in several ways to activate the mouse but I couldn't 

### Extension Version

3.0

### What browser(s) are you seeing the problem on?

Other (Please specify)

### Other browser

Kiwi Browser Android

**Comment by Oxdf22** [comment]
![Uploading Screenshot_20221008-143054.png…]()

**Comment by Oxdf22** [comment]
![Screenshot_20221008-143054](https://user-images.githubusercontent.com/115331193/194720367-a6b949ac-af4e-4f21-a472-9a48069144be.png)

**Comment by idolize** [comment]
Duplicate of #20
