### ISSUE TITLE
Won't connect to my game.

### ISSUE THREAD

**Issue by unnamed1829** [idolize/xcloud-keyboard-mouse#84]
### Bug description

i have tried a couple of games now not sure if i have missed a step. it wont connect strait to the game i wanna play. (fallout 3, PowerWash Simulator) what would the issue be? if it is me then all good but i cant figure it out. the use button wont light up either

### Extension Version

3.1

### What browser(s) are you seeing the problem on?

Chrome

**Comment by unnamed1829** [comment]
never mind it seems to have fixed iteself i think im the problem :D work great thank you guys

**Comment by idolize** [comment]
Awesome!
