### ISSUE TITLE
the welcome pop up doesn't go away

### ISSUE THREAD

**Issue by QuackGH** [idolize/xcloud-keyboard-mouse#88]
### Bug description

Whenever I click Understood in the welcome thing it just pops back up and it does that everytime I click Understood

### Extension Version

3.1

### What browser(s) are you seeing the problem on?

Chrome

**Comment by idolize** [comment]
I have added a change in version 3.2 (and 3.3, which is in review) that should address this for the users that were having issues with Chrome storage sync.
