### ISSUE TITLE
mouse move out of control playing FN since 3.2

### ISSUE THREAD

**Issue by sebplais** [idolize/xcloud-keyboard-mouse#93]
### Bug description

Since latest upgrade 3.2 mouse is behaving randomly , sometimes move are ok sometimes no response at all , impossible to play at Fortnite with it
extension on Chrome  108.0.5359.125 playing Fortnite xbox cloud  / Windows 10

### Extension Version

3.2

### What browser(s) are you seeing the problem on?

Chrome

### Browser version number

108.0.5359.125

**Comment by idolize** [comment]
Thanks - this should be restored to the previous behavior in version 3.3 which is in review right now (should go live in a day or so)

**Comment by idolize** [comment]
3.3 is live now and should resolve this!
