### ISSUE TITLE
Conflict in the halfway-point when moving camera to diagonals.

### ISSUE THREAD

**Issue by lSiegfriedl** [idolize/xcloud-keyboard-mouse#95]
## Problem

I've been playing Skyrim and had trouble moving the camera. Whenever I point the mouse at a diagonal it starts to go too slow and the movement conflicts some times at the halfway-point. I think this conflict is due to the mouse emulator not moving at all in all directions, just 90° and 45° (up, down, left, right and diagonals).

## Suggested solution

You may need to add the other degrees to the 360° amount for it to move correctly, just like it does on the Xbox controller.

## Alternatives

Maybe prevent directions from switching when moving the mouse diagonally.

**Comment by idolize** [comment]
Thanks for your help @lSiegfriedl - this should be restored to the previous behavior in version 3.3 which is in review right now (should go live in a day or so)

**Comment by idolize** [comment]
3.3 is live now and should resolve this!
