### ISSUE TITLE
Bad sensitivity and extension being paid

### ISSUE THREAD

**Issue by TioMooNzi** [idolize/xcloud-keyboard-mouse#96]
### Bug description

After this last update, in addition to the extension starting to be paid, the mouse has a sensitivity problem and everyone is complaining about it, it's sad that you charge for something like that.

### Extension Version

108.0.5359.128.

### What browser(s) are you seeing the problem on?

Chrome, Other (Please specify)

### Other browser

Brave

### Browser version number

108.0.5359.128.

**Comment by Hfhdhdhf** [comment]
I got it its now free trial only and u only have 3 days to use it or else u need to pay, lets go to REWASD

**Comment by TioMooNzi** [comment]
They haven't fixed the sensitivity yet, when I play fortnite the
sensitivity is extremely slow to the point that it doesn't even move, and
yes, now the extension will be paid, leaving only 3 days of free use.

Em ter, 10 de jan de 2023 11:35, Hfhdhdhf ***@***.***>
escreveu:

**Comment by gustavo-ticto** [comment]
I'm facing same issues here as well

**Comment by tcsayto** [comment]
estou com o mesmo problema referente a sensibilidade . já comprei a extensão porem quero um reembolso já que não consigo usar a extensão da maneira que ela esta agora

**Comment by idolize** [comment]
Hey, sorry you are having issues. I did tweak one thing in 3.2 to reduce the time it takes after you finish moving the mouse before resetting the virtual "stick" back to center (because some others complained about it feeling like a slight lag after moving).

I am going to release a hotfix 3.3 to revert that back to how it was in 3.1.

**Comment by TIOZINdaMAGIA** [comment]
i am suffering the same problem. in addition, the extension was paid out of nowhere

**Comment by idolize** [comment]
3.3 is live now and should resolve this!
