### ISSUE TITLE
Camera movement problem

### ISSUE THREAD

**Issue by lSiegfriedl** [idolize/xcloud-keyboard-mouse#97]
## Problem

Can anyone help me? The camera movement is really bad, this emulates an xbox controller and a mouse doesn't work that way. Whenever I point the mouse at a diagonal it starts to go too slow and the movement conflicts some times at the halfway-point. If this problem can't be solved, i want a refund.

**Comment by sebplais** [comment]
same issue as #93  and #96

**Comment by tcsayto** [comment]
estou com o mesmo problema referente a sensibilidade . já comprei a extensão porem quero um reembolso já que não consigo usar a extensão da maneira que ela esta agora

**Comment by idolize** [comment]
Thanks for your help @lSiegfriedl - this should be restored to the previous behavior in version 3.3 which is in review right now (should go live in a day or so)

**Comment by FelipePy** [comment]
I have the same problem

**Comment by Andersonon** [comment]
I'm having the same problem, it started earlier, first a mandatory purchase option appeared to have access to the extension, so far so good I bought it and then it got horrible I'm unable to play, especially moving the mouse generates a very high lag it looks like the internet is weak but just deactivate the extension and put a controller on xcloud that returns everything to normal, but I don't like to play with the controller I like the mouse and keyboard solve this please the payment has already been made, we pay to have something worse ?

**Comment by idolize** [comment]
@Andersonon the fix is in review right now with Google. Should go live as soon as they approve it. Sorry for the trouble - it's as fast as I can go.

**Comment by idolize** [comment]
3.3 is live now and should resolve this!
