### ISSUE TITLE
NÃO FUNCIONA CORRETAMENTE COMO ANTES, CASO O PROBLEMA NAO SEJA RESOLVIDO, QUERO REEMBOLSO

### ISSUE THREAD

**Issue by NightxCrow** [idolize/xcloud-keyboard-mouse#98]
### Bug description

A extensão está com algum tipo de problema, fazendo com que o movimento do mouse em certos momentos nao funciona ou funciona mal, ao arrastar para os lados, arrasta com uma sensação de travamento, nao faz o movimento liso do jeito que era....a alguma previsão de quando será corrigio?

### Extension Version

3.2

### What browser(s) are you seeing the problem on?

Microsoft Edge

**Comment by polarisuy** [comment]
estou com o mesmo problema, nao da pra jogar assim

**Comment by idolize** [comment]
Estou esperando a versão 3.3 entrar no ar (deve levar apenas cerca de um dia), mas essa versão deve restaurar a sensibilidade do mouse exatamente como era antes. Obrigada! Desculpe por qualquer problema.
