### ISSUE TITLE
mouse movement broken

### ISSUE THREAD

**Issue by polarisuy** [idolize/xcloud-keyboard-mouse#99]
### Bug description

in 3.2 the mouse movement is broken!

### Extension Version

3.2

### What browser(s) are you seeing the problem on?

Chrome

**Comment by FelipePy** [comment]
I have the same problem

**Comment by idolize** [comment]
Thanks for letting me know. I've reverted the changes to the movement from 3.2 in a new hotfix release **3.3** which is currently in review and should be live on the Chrome store in about a day.

**Comment by FelipePy** [comment]
Thanks for listening!

**Comment by idolize** [comment]
3.3 is live now and should resolve this!
